TEAM_REGISTRY = [

# canonical | bart | odds | espn

{"canonical":"Drake","bart":"Drake","odds":"Drake","espn":"Drake Bulldogs"},
{"canonical":"Sacred Heart","bart":"Sacred Heart","odds":"Sacred Heart","espn":"Sacred Heart Pioneers"},
{"canonical":"Southern Illinois","bart":"Southern Illinois","odds":"Southern Illinois","espn":"Southern Illinois Salukis"},
{"canonical":"South Carolina St.","bart":"South Carolina St.","odds":"South Carolina St.","espn":"South Carolina State Bulldogs"},
{"canonical":"Boston University","bart":"Boston University","odds":"","espn":"Boston University Terriers"},
{"canonical":"Loyola MD","bart":"Loyola MD","odds":"Loyola MD","espn":"Loyola Maryland Greyhounds"},
{"canonical":"Loyola Marymount","bart":"Loyola Marymount","odds":"Loyola Marymount","espn":"Loyola Marymount Lions"},
{"canonical":"Pepperdine","bart":"Pepperdine","odds":"Pepperdine","espn":"Pepperdine Waves"},
{"canonical":"Portland","bart":"Portland","odds":"Portland","espn":"Portland Pilots"},
{"canonical":"Valparaiso","bart":"Valparaiso","odds":"Valparaiso","espn":"Valparaiso Beacons"},
{"canonical":"Fairfield","bart":"Fairfield","odds":"Fairfield","espn":"Fairfield Stags"},
{"canonical":"Iona","bart":"Iona","odds":"Iona","espn":"Iona Gaels"},
{"canonical":"Bucknell","bart":"Bucknell","odds":"Bucknell","espn":"Bucknell Bison"},
{"canonical":"Navy","bart":"Navy","odds":"Navy","espn":"Navy Midshipmen"},
{"canonical":"Holy Cross","bart":"Holy Cross","odds":"Holy Cross","espn":"Holy Cross Crusaders"},
{"canonical":"Lehigh","bart":"Lehigh","odds":"Lehigh","espn":"Lehigh Mountain Hawks"},
{"canonical":"Manhattan","bart":"Manhattan","odds":"Manhattan","espn":"Manhattan Jaspers"},
{"canonical":"Ohio","bart":"Ohio","odds":"Ohio","espn":"Ohio Bobcats"},
{"canonical":"Miami OH","bart":"Miami OH","odds":"Miami OH","espn":"Miami (OH) RedHawks"},
{"canonical":"Michigan","bart":"Michigan","odds":"Michigan","espn":"Michigan Wolverines"},
{"canonical":"Iowa","bart":"Iowa","odds":"Iowa","espn":"Iowa Hawkeyes"},
{"canonical":"Oral Roberts","bart":"Oral Roberts","odds":"Oral Roberts","espn":"Oral Roberts Golden Eagles"},
{"canonical":"North Dakota St.","bart":"North Dakota St.","odds":"North Dakota St.","espn":"North Dakota State Bison"},
{"canonical":"San Diego","bart":"San Diego","odds":"San Diego","espn":"San Diego Toreros"},
{"canonical":"South Dakota St.","bart":"South Dakota St.","odds":"South Dakota St.","espn":"South Dakota State Jackrabbits"},
{"canonical":"St. Thomas","bart":"St. Thomas","odds":"St. Thomas","espn":"St. Thomas-Minnesota Tommies"},
{"canonical":"James Madison","bart":"James Madison","odds":"James Madison","espn":"James Madison Dukes"},
{"canonical":"Southern Miss","bart":"Southern Miss","odds":"Southern Miss","espn":"Southern Miss Golden Eagles"},
{"canonical":"Sam Houston St.","bart":"Sam Houston St.","odds":"Sam Houston St.","espn":"Sam Houston Bearkats"},
{"canonical":"Delaware","bart":"Delaware","odds":"Delaware","espn":"Delaware Blue Hens"},
{"canonical":"Delaware St.","bart":"Delaware St.","odds":"Delaware St.","espn":"Delaware State Hornets"},
{"canonical":"Maryland Eastern Shore","bart":"Maryland Eastern Shore","odds":"Maryland Eastern Shore","espn":"Maryland Eastern Shore Hawks"},
{"canonical":"Tulsa","bart":"Tulsa","odds":"Tulsa","espn":"Tulsa Golden Hurricane"},
{"canonical":"East Carolina","bart":"East Carolina","odds":"East Carolina","espn":"East Carolina Pirates"},
{"canonical":"Temple","bart":"Temple","odds":"Temple","espn":"Temple Owls"},
{"canonical":"Tulane","bart":"Tulane","odds":"Tulane","espn":"Tulane Green Wave"},
{"canonical":"UC Davis","bart":"UC Davis","odds":"UC Davis","espn":"UC Davis Aggies"},
{"canonical":"UC Irvine","bart":"UC Irvine","odds":"UC Irvine","espn":"UC Irvine Anteaters"},
{"canonical":"UC Riverside","bart":"UC Riverside","odds":"UC Riverside","espn":"UC Riverside Highlanders"},
{"canonical":"UTEP","bart":"UTEP","odds":"UTEP","espn":"UTEP Miners"},
{"canonical":"Utah Valley","bart":"Utah Valley","odds":"Utah Valley","espn":"Utah Valley Wolverines"},
{"canonical":"Western Kentucky","bart":"Western Kentucky","odds":"Western Kentucky","espn":"Western Kentucky Hilltoppers"},
{"canonical":"Abilene Christian","bart":"Abilene Christian","odds":"","espn":"Abilene Christian Wildcats"},
{"canonical":"Alabama A&M","bart":"Alabama A&M","odds":"","espn":"Alabama A&M Bulldogs"},
{"canonical":"Alabama St.","bart":"Alabama St.","odds":"","espn":"Alabama St Hornets"},
{"canonical":"Alcorn St.","bart":"Alcorn St.","odds":"","espn":"Alcorn St Braves"},
{"canonical":"American","bart":"American","odds":"","espn":"American Eagles"},
{"canonical":"Arkansas St.","bart":"Arkansas St.","odds":"","espn":"Arkansas St Red Wolves"},
{"canonical":"Arkansas Pine Bluff","bart":"Arkansas Pine Bluff","odds":"","espn":"Arkansas-Pine Bluff Golden Lions"},
{"canonical":"Bethune Cookman","bart":"Bethune Cookman","odds":"","espn":"Bethune-Cookman Wildcats"},
{"canonical":"Boston University","bart":"Boston University","odds":"","espn":"Boston Univ. Terriers"},
{"canonical":"Cal St. Bakersfield","bart":"Cal St. Bakersfield","odds":"","espn":"CSU Bakersfield Roadrunners"},
{"canonical":"Cal St. Fullerton","bart":"Cal St. Fullerton","odds":"","espn":"CSU Fullerton Titans"},
{"canonical":"Cal St. Northridge","bart":"Cal St. Northridge","odds":"","espn":"CSU Northridge Matadors"},
{"canonical":"Cal Baptist","bart":"Cal Baptist","odds":"Cal Baptist Lancers","espn":"Cal Baptist Lancers"},
{"canonical":"Cal Poly","bart":"Cal Poly","odds":"","espn":"Cal Poly Mustangs"},
{"canonical":"Colgate","bart":"Colgate","odds":"","espn":"Colgate Raiders"},
{"canonical":"Coppin St.","bart":"Coppin St.","odds":"","espn":"Coppin St Eagles"},
{"canonical":"Delaware St.","bart":"Delaware St.","odds":"","espn":"Delaware St Hornets"},
{"canonical":"Eastern Illinois","bart":"Eastern Illinois","odds":"","espn":"Eastern Illinois Panthers"},
{"canonical":"Evansville","bart":"Evansville","odds":"","espn":"Evansville Purple Aces"},
{"canonical":"Florida A&M","bart":"Florida A&M","odds":"","espn":"Florida A&M Rattlers"},
{"canonical":"FIU","bart":"FIU","odds":"","espn":"Florida Int'l Golden Panthers"},
{"canonical":"Georgia Southern","bart":"Georgia Southern","odds":"","espn":"Georgia Southern Eagles"},
{"canonical":"Grambling St.","bart":"Grambling St.","odds":"","espn":"Grambling St Tigers"},
{"canonical":"Hawaii","bart":"Hawaii","odds":"","espn":"Hawai'i Rainbow Warriors"},
{"canonical":"Howard","bart":"Howard","odds":"","espn":"Howard Bison"},
{"canonical":"Indiana St.","bart":"Indiana St.","odds":"","espn":"Indiana St Sycamores"},
{"canonical":"Jackson St.","bart":"Jackson St.","odds":"","espn":"Jackson St Tigers"},
{"canonical":"Jacksonville St.","bart":"Jacksonville St.","odds":"","espn":"Jacksonville St Gamecocks"},
{"canonical":"Kennesaw St.","bart":"Kennesaw St.","odds":"","espn":"Kennesaw St Owls"},
{"canonical":"Liberty","bart":"Liberty","odds":"","espn":"Liberty Flames"},
{"canonical":"Lindenwood","bart":"Lindenwood","odds":"Lindenwood Lions","espn":"Lindenwood Lions"},
{"canonical":"Long Beach St.","bart":"Long Beach St.","odds":"","espn":"Long Beach St 49ers"},
{"canonical":"Louisiana Tech","bart":"Louisiana Tech","odds":"","espn":"Louisiana Tech Bulldogs"},
{"canonical":"Loyola MD","bart":"Loyola MD","odds":"","espn":"Loyola (MD) Greyhounds"},
{"canonical":"Maryland Eastern Shore","bart":"Maryland Eastern Shore","odds":"","espn":"Maryland-Eastern Shore Hawks"},
{"canonical":"Memphis","bart":"Memphis","odds":"","espn":"Memphis Tigers"},
{"canonical":"Michigan St.","bart":"Michigan St.","odds":"","espn":"Michigan St Spartans"},
{"canonical":"Middle Tennessee","bart":"Middle Tennessee","odds":"","espn":"Middle Tennessee Blue Raiders"},
{"canonical":"Mississippi Valley St.","bart":"Mississippi Valley St.","odds":"","espn":"Miss Valley St Delta Devils"},
{"canonical":"Missouri St.","bart":"Missouri St.","odds":"","espn":"Missouri St Bears"},
{"canonical":"Morgan St.","bart":"Morgan St.","odds":"","espn":"Morgan St Bears"},
{"canonical":"New Mexico St.","bart":"New Mexico St.","odds":"","espn":"New Mexico St Aggies"},
{"canonical":"Norfolk St.","bart":"Norfolk St.","odds":"","espn":"Norfolk St Spartans"},
{"canonical":"North Carolina Central","bart":"North Carolina Central","odds":"","espn":"North Carolina Central Eagles"},
{"canonical":"North Dakota St.","bart":"North Dakota St.","odds":"","espn":"North Dakota St Bison"},
{"canonical":"Northern Iowa","bart":"Northern Iowa","odds":"","espn":"Northern Iowa Panthers"},
{"canonical":"Prairie View A&M","bart":"Prairie View A&M","odds":"","espn":"Prairie View Panthers"},
{"canonical":"Rutgers","bart":"Rutgers","odds":"","espn":"Rutgers Scarlet Knights"},
{"canonical":"Southeast Missouri St.","bart":"Southeast Missouri St.","odds":"","espn":"SE Missouri St Redhawks"},
{"canonical":"Sam Houston St.","bart":"Sam Houston St.","odds":"","espn":"Sam Houston St Bearkats"},
{"canonical":"South Carolina St.","bart":"South Carolina St.","odds":"","espn":"South Carolina St Bulldogs"},
{"canonical":"South Dakota St.","bart":"South Dakota St.","odds":"","espn":"South Dakota St Jackrabbits"},
{"canonical":"South Florida","bart":"South Florida","odds":"","espn":"South Florida Bulls"},
{"canonical":"Southern","bart":"Southern","odds":"","espn":"Southern Jaguars"},
{"canonical":"Southern Utah","bart":"Southern Utah","odds":"","espn":"Southern Utah Thunderbirds"},
{"canonical":"St. Thomas","bart":"St. Thomas","odds":"","espn":"St. Thomas (MN) Tommies"},
{"canonical":"Tarleton St.","bart":"Tarleton St.","odds":"","espn":"Tarleton State Texans"},
{"canonical":"Tennessee Martin","bart":"Tennessee Martin","odds":"","espn":"Tenn-Martin Skyhawks"},
{"canonical":"Texas Southern","bart":"Texas Southern","odds":"","espn":"Texas Southern Tigers"},
{"canonical":"UC San Diego","bart":"UC San Diego","odds":"","espn":"UC San Diego Tritons"},
{"canonical":"UT Arlington","bart":"UT Arlington","odds":"","espn":"UT-Arlington Mavericks"},
]
