TEAM_REGISTRY = [

{"canonical":"Akron","bart":"Akron","odds":"Akron Zips","espn":""},
{"canonical":"Alabama","bart":"Alabama","odds":"Alabama Crimson Tide","espn":""},
{"canonical":"Arizona St.","bart":"Arizona St.","odds":"Arizona St Sun Devils","espn":""},
{"canonical":"Arizona","bart":"Arizona","odds":"Arizona Wildcats","espn":""},
{"canonical":"Arkansas","bart":"Arkansas","odds":"Arkansas Razorbacks","espn":""},
{"canonical":"Auburn","bart":"Auburn","odds":"Auburn Tigers","espn":""},
{"canonical":"Austin Peay","bart":"Austin Peay","odds":"Austin Peay Governors","espn":""},
{"canonical":"Ball St.","bart":"Ball St.","odds":"Ball State Cardinals","espn":""},
{"canonical":"Bellarmine","bart":"Bellarmine","odds":"Bellarmine Knights","espn":""},
{"canonical":"Belmont","bart":"Belmont","odds":"Belmont Bruins","espn":""},
{"canonical":"Bowling Green","bart":"Bowling Green","odds":"Bowling Green Falcons","espn":""},
{"canonical":"Bradley","bart":"Bradley","odds":"Bradley Braves","espn":""},
{"canonical":"Brown","bart":"Brown","odds":"Brown Bears","espn":""},
{"canonical":"Buffalo","bart":"Buffalo","odds":"Buffalo Bulls","espn":""},
{"canonical":"Central Arkansas","bart":"Central Arkansas","odds":"Central Arkansas Bears","espn":""},
{"canonical":"Central Michigan","bart":"Central Michigan","odds":"Central Michigan Chippewas","espn":""},
{"canonical":"Charleston Southern","bart":"Charleston Southern","odds":"Charleston Southern Buccaneers","espn":""},
{"canonical":"Chattanooga","bart":"Chattanooga","odds":"Chattanooga Mocs","espn":""},
{"canonical":"Colorado","bart":"Colorado","odds":"Colorado Buffaloes","espn":""},
{"canonical":"Columbia","bart":"Columbia","odds":"Columbia Lions","espn":""},
{"canonical":"Dayton","bart":"Dayton","odds":"Dayton Flyers","espn":""},
{"canonical":"Denver","bart":"Denver","odds":"Denver Pioneers","espn":""},
{"canonical":"Drake","bart":"Drake","odds":"Drake","espn":""},
{"canonical":"Duke","bart":"Duke","odds":"Duke Blue Devils","espn":""},
{"canonical":"Eastern Michigan","bart":"Eastern Michigan","odds":"Eastern Michigan Eagles","espn":""},
{"canonical":"Fairfield","bart":"Fairfield","odds":"Fairfield","espn":""},
{"canonical":"Florida","bart":"Florida","odds":"Florida Gators","espn":""},
{"canonical":"Florida Gulf Coast","bart":"Florida Gulf Coast","odds":"Florida Gulf Coast Eagles","espn":""},
{"canonical":"Gardner Webb","bart":"Gardner Webb","odds":"Gardner-Webb Bulldogs","espn":""},
{"canonical":"George Mason","bart":"George Mason","odds":"George Mason Patriots","espn":""},
{"canonical":"Georgia Southern","bart":"Georgia Southern","odds":"Georgia Southern","espn":""},
{"canonical":"Harvard","bart":"Harvard","odds":"Harvard Crimson","espn":""},
{"canonical":"High Point","bart":"High Point","odds":"High Point Panthers","espn":""},
{"canonical":"Houston","bart":"Houston","odds":"Houston Cougars","espn":""},
{"canonical":"Illinois St.","bart":"Illinois St.","odds":"Illinois St Redbirds","espn":""},
{"canonical":"Iowa St.","bart":"Iowa St.","odds":"Iowa State Cyclones","espn":""},
{"canonical":"Kansas","bart":"Kansas","odds":"Kansas Jayhawks","espn":""},
{"canonical":"Kansas St.","bart":"Kansas St.","odds":"Kansas St Wildcats","espn":""},
{"canonical":"Kent St.","bart":"Kent St.","odds":"Kent State Golden Flashes","espn":""},
{"canonical":"Kentucky","bart":"Kentucky","odds":"Kentucky Wildcats","espn":""},
{"canonical":"Lipscomb","bart":"Lipscomb","odds":"Lipscomb Bisons","espn":""},
{"canonical":"Longwood","bart":"Longwood","odds":"Longwood Lancers","espn":""},
{"canonical":"Louisville","bart":"Louisville","odds":"Louisville Cardinals","espn":""},
{"canonical":"Marquette","bart":"Marquette","odds":"Marquette Golden Eagles","espn":""},
{"canonical":"Merrimack","bart":"Merrimack","odds":"Merrimack Warriors","espn":""},
{"canonical":"Miami FL","bart":"Miami FL","odds":"Miami Hurricanes","espn":"Miami"},
{"canonical":"Miami OH","bart":"Miami OH","odds":"Miami RedHawks","espn":""},
{"canonical":"Miami OH","bart":"Miami (OH)","odds":"Miami (OH) RedHawks","espn":"Miami OH RedHawks"},
{"canonical":"Missouri","bart":"Missouri","odds":"Missouri Tigers","espn":""},
{"canonical":"Morehead St.","bart":"Morehead St.","odds":"Morehead St Eagles","espn":""},
{"canonical":"Murray St.","bart":"Murray St.","odds":"Murray St Racers","espn":""},
{"canonical":"North Carolina A&T","bart":"North Carolina A&T","odds":"North Carolina A&T Aggies","espn":""},
{"canonical":"North Carolina","bart":"North Carolina","odds":"North Carolina Tar Heels","espn":""},
{"canonical":"North Dakota","bart":"North Dakota","odds":"North Dakota Fighting Hawks","espn":""},
{"canonical":"Northeastern","bart":"Northeastern","odds":"Northeastern Huskies","espn":""},
{"canonical":"Northern Illinois","bart":"Northern Illinois","odds":"Northern Illinois Huskies","espn":""},
{"canonical":"Northern Iowa","bart":"Northern Iowa","odds":"Northern Iowa","espn":""},
{"canonical":"Ohio","bart":"Ohio","odds":"Ohio","espn":""},
{"canonical":"Oklahoma St.","bart":"Oklahoma St.","odds":"Oklahoma St Cowboys","espn":""},
{"canonical":"Omaha","bart":"Nebraska Omaha","odds":"Omaha Mavericks","espn":""},
{"canonical":"Penn","bart":"Penn","odds":"Pennsylvania Quakers","espn":""},
{"canonical":"Portland","bart":"Portland","odds":"Portland","espn":""},
{"canonical":"Presbyterian","bart":"Presbyterian","odds":"Presbyterian Blue Hose","espn":""},
{"canonical":"Purdue","bart":"Purdue","odds":"Purdue Boilermakers","espn":""},
{"canonical":"Queens","bart":"Queens","odds":"Queens University Royals","espn":""},
{"canonical":"Radford","bart":"Radford","odds":"Radford Highlanders","espn":""},
{"canonical":"Sacred Heart","bart":"Sacred Heart","odds":"Sacred Heart","espn":""},
{"canonical":"Saint Louis","bart":"Saint Louis","odds":"Saint Louis Billikens","espn":""},
{"canonical":"Saint Peter's","bart":"Saint Peter's","odds":"Saint Peter's Peacocks","espn":""},
{"canonical":"San Diego","bart":"San Diego","odds":"San Diego Toreros","espn":""},
{"canonical":"San Diego St.","bart":"San Diego St.","odds":"San Diego St Aztecs","espn":""},
{"canonical":"Seattle","bart":"Seattle","odds":"Seattle Redhawks","espn":""},
{"canonical":"Seton Hall","bart":"Seton Hall","odds":"Seton Hall Pirates","espn":""},
{"canonical":"South Alabama","bart":"South Alabama","odds":"South Alabama Jaguars","espn":""},
{"canonical":"South Dakota","bart":"South Dakota","odds":"South Dakota Coyotes","espn":""},
{"canonical":"Southeast Missouri St.","bart":"Southeast Missouri St.","odds":"Southeast Missouri St.","espn":""},
{"canonical":"Southern Miss","bart":"Southern Miss","odds":"Southern Miss","espn":""},
{"canonical":"St. John's","bart":"St. John's","odds":"St. John's Red Storm","espn":""},
{"canonical":"Stetson","bart":"Stetson","odds":"Stetson Hatters","espn":""},
{"canonical":"Tennessee Martin","bart":"Tennessee Martin","odds":"Tennessee Martin","espn":""},
{"canonical":"Tennessee St.","bart":"Tennessee St.","odds":"Tennessee St Tigers","espn":""},
{"canonical":"Tennessee","bart":"Tennessee","odds":"Tennessee Volunteers","espn":""},
{"canonical":"Texas St.","bart":"Texas St.","odds":"Texas State Bobcats","espn":""},
{"canonical":"The Citadel","bart":"The Citadel","odds":"The Citadel Bulldogs","espn":""},
{"canonical":"Toledo","bart":"Toledo","odds":"Toledo Rockets","espn":""},
{"canonical":"UCF","bart":"UCF","odds":"UCF Knights","espn":""},
{"canonical":"Connecticut","bart":"Connecticut","odds":"UConn Huskies","espn":""},
{"canonical":"Illinois Chicago","bart":"Illinois Chicago","odds":"UIC Flames","espn":""},
{"canonical":"UNC Asheville","bart":"UNC Asheville","odds":"UNC Asheville Bulldogs","espn":""},
{"canonical":"UNC Greensboro","bart":"UNC Greensboro","odds":"UNC Greensboro Spartans","espn":""},
{"canonical":"UNLV","bart":"UNLV","odds":"UNLV Rebels","espn":""},
{"canonical":"VCU","bart":"VCU","odds":"VCU Rams","espn":""},
{"canonical":"VMI","bart":"VMI","odds":"VMI Keydets","espn":""},
{"canonical":"Valparaiso","bart":"Valparaiso","odds":"Valparaiso","espn":""},
{"canonical":"Vanderbilt","bart":"Vanderbilt","odds":"Vanderbilt Commodores","espn":""},
{"canonical":"Virginia","bart":"Virginia","odds":"Virginia Cavaliers","espn":""},
{"canonical":"Virginia Tech","bart":"Virginia Tech","odds":"Virginia Tech Hokies","espn":""},
{"canonical":"Washington St.","bart":"Washington St.","odds":"Washington St Cougars","espn":""},
{"canonical":"West Georgia","bart":"West Georgia","odds":"West Georgia Wolves","espn":""},
{"canonical":"West Virginia","bart":"West Virginia","odds":"West Virginia Mountaineers","espn":""},
{"canonical":"Western Michigan","bart":"Western Michigan","odds":"Western Michigan Broncos","espn":""},
{"canonical":"Winthrop","bart":"Winthrop","odds":"Winthrop Eagles","espn":""},
{"canonical":"Wisconsin","bart":"Wisconsin","odds":"Wisconsin Badgers","espn":""},
{"canonical":"Campbell","bart":"Campbell","odds":"Campbell Fighting Camels","espn":""},
{"canonical":"Stony Brook","bart":"Stony Brook","odds":"Stony Brook Seawolves","espn":""},
{"canonical":"Davidson","bart":"Davidson","odds":"Davidson Wildcats","espn":""},
{"canonical":"St. Bonaventure","bart":"St. Bonaventure","odds":"St. Bonaventure Bonnies","espn":""},
{"canonical":"Louisiana Tech","bart":"Louisiana Tech","odds":"Louisiana Tech Bulldogs","espn":""},
{"canonical":"Delaware","bart":"Delaware","odds":"Delaware Blue Hens","espn":""},
{"canonical":"Stonehill","bart":"Stonehill","odds":"Stonehill Skyhawks","espn":""},
{"canonical":"Mercyhurst","bart":"Mercyhurst","odds":"Mercyhurst Lakers","espn":""},
{"canonical":"East Tennessee St.","bart":"East Tennessee St.","odds":"East Tennessee St Buccaneers","espn":""},
{"canonical":"Clemson","bart":"Clemson","odds":"Clemson Tigers","espn":""},
{"canonical":"Georgia Tech","bart":"Georgia Tech","odds":"Georgia Tech Yellow Jackets","espn":""},
{"canonical":"Abilene Christian","bart":"Abilene Christian","odds":"Abilene Christian Wildcats","espn":""},
{"canonical":"Air Force","bart":"Air Force","odds":"Air Force Falcons","espn":""},
{"canonical":"Albany","bart":"Albany","odds":"Albany Great Danes","espn":""},
{"canonical":"Appalachian St.","bart":"Appalachian St.","odds":"Appalachian St Mountaineers","espn":""},
{"canonical":"BYU","bart":"BYU","odds":"BYU Cougars","espn":""},
{"canonical":"Baylor","bart":"Baylor","odds":"Baylor Bears","espn":""},
{"canonical":"Boise St.","bart":"Boise St.","odds":"Boise State Broncos","espn":""},
{"canonical":"Boston College","bart":"Boston College","odds":"Boston College Eagles","espn":""},
{"canonical":"Bryant","bart":"Bryant","odds":"Bryant Bulldogs","espn":""},
{"canonical":"Butler","bart":"Butler","odds":"Butler Bulldogs","espn":""},
{"canonical":"Cal St. Bakersfield","bart":"Cal St. Bakersfield","odds":"CSU Bakersfield Roadrunners","espn":""},
{"canonical":"Cal St. Fullerton","bart":"Cal St. Fullerton","odds":"CSU Fullerton Titans","espn":""},
{"canonical":"Cal St. Northridge","bart":"Cal St. Northridge","odds":"CSU Northridge Matadors","espn":""},
{"canonical":"Cal Baptist","bart":"Cal Baptist","odds":"Cal Baptist Lancers","espn":""},
{"canonical":"Cal Poly","bart":"Cal Poly","odds":"Cal Poly Mustangs","espn":""},
{"canonical":"California","bart":"California","odds":"California Golden Bears","espn":""},
{"canonical":"Cincinnati","bart":"Cincinnati","odds":"Cincinnati Bearcats","espn":""},
{"canonical":"Coastal Carolina","bart":"Coastal Carolina","odds":"Coastal Carolina Chanticleers","espn":""},
{"canonical":"Colorado St.","bart":"Colorado St.","odds":"Colorado St Rams","espn":""},
{"canonical":"Cornell","bart":"Cornell","odds":"Cornell Big Red","espn":""},
{"canonical":"Dartmouth","bart":"Dartmouth","odds":"Dartmouth Big Green","espn":""},
{"canonical":"DePaul","bart":"DePaul","odds":"DePaul Blue Demons","espn":""},
{"canonical":"Drexel","bart":"Drexel","odds":"Drexel Dragons","espn":""},
{"canonical":"Duquesne","bart":"Duquesne","odds":"Duquesne Dukes","espn":""},
{"canonical":"Elon","bart":"Elon","odds":"Elon Phoenix","espn":""},
{"canonical":"Florida Atlantic","bart":"Florida Atlantic","odds":"Florida Atlantic Owls","espn":""},
{"canonical":"FIU","bart":"FIU","odds":"Florida Int'l Golden Panthers","espn":""},
{"canonical":"Florida St.","bart":"Florida St.","odds":"Florida St Seminoles","espn":""},
{"canonical":"Fordham","bart":"Fordham","odds":"Fordham Rams","espn":""},
{"canonical":"Fresno St.","bart":"Fresno St.","odds":"Fresno St Bulldogs","espn":""},
{"canonical":"Furman","bart":"Furman","odds":"Furman Paladins","espn":""},
{"canonical":"George Washington","bart":"George Washington","odds":"GW Revolutionaries","espn":""},
{"canonical":"Georgetown","bart":"Georgetown","odds":"Georgetown Hoyas","espn":""},
{"canonical":"Georgia","bart":"Georgia","odds":"Georgia Bulldogs","espn":""},
{"canonical":"Grand Canyon","bart":"Grand Canyon","odds":"Grand Canyon Antelopes","espn":""},
{"canonical":"Hampton","bart":"Hampton","odds":"Hampton Pirates","espn":""},
{"canonical":"Hawaii","bart":"Hawaii","odds":"Hawai'i Rainbow Warriors","espn":""},
{"canonical":"Idaho","bart":"Idaho","odds":"Idaho Vandals","espn":""},
{"canonical":"Idaho St.","bart":"Idaho St.","odds":"Idaho State Bengals","espn":""},
{"canonical":"Indiana","bart":"Indiana","odds":"Indiana Hoosiers","espn":""},
{"canonical":"Jacksonville St.","bart":"Jacksonville St.","odds":"Jacksonville St Gamecocks","espn":""},
{"canonical":"Kennesaw St.","bart":"Kennesaw St.","odds":"Kennesaw St Owls","espn":""},
{"canonical":"LIU","bart":"LIU","odds":"LIU Sharks","espn":""},
{"canonical":"LSU","bart":"LSU","odds":"LSU Tigers","espn":""},
{"canonical":"La Salle","bart":"La Salle","odds":"La Salle Explorers","espn":""},
{"canonical":"Liberty","bart":"Liberty","odds":"Liberty Flames","espn":""},
{"canonical":"Long Beach St.","bart":"Long Beach St.","odds":"Long Beach St 49ers","espn":""},
{"canonical":"Loyola Chicago","bart":"Loyola Chicago","odds":"Loyola (Chi) Ramblers","espn":""},
{"canonical":"Maine","bart":"Maine","odds":"Maine Black Bears","espn":""},
{"canonical":"Marist","bart":"Marist","odds":"Marist Red Foxes","espn":""},
{"canonical":"Mercer","bart":"Mercer","odds":"Mercer Bears","espn":""},
{"canonical":"Middle Tennessee","bart":"Middle Tennessee","odds":"Middle Tennessee Blue Raiders","espn":""},
{"canonical":"Minnesota","bart":"Minnesota","odds":"Minnesota Golden Gophers","espn":""},
{"canonical":"Mississippi St.","bart":"Mississippi St.","odds":"Mississippi St Bulldogs","espn":""},
{"canonical":"Missouri St.","bart":"Missouri St.","odds":"Missouri St Bears","espn":""},
{"canonical":"Mount St. Mary's","bart":"Mount St. Mary's","odds":"Mt. St. Mary's Mountaineers","espn":""},
{"canonical":"N.C. State","bart":"N.C. State","odds":"NC State Wolfpack","espn":""},
{"canonical":"NJIT","bart":"NJIT","odds":"NJIT Highlanders","espn":""},
{"canonical":"Nevada","bart":"Nevada","odds":"Nevada Wolf Pack","espn":""},
{"canonical":"New Hampshire","bart":"New Hampshire","odds":"New Hampshire Wildcats","espn":""},
{"canonical":"New Mexico","bart":"New Mexico","odds":"New Mexico Lobos","espn":""},
{"canonical":"New Mexico St.","bart":"New Mexico St.","odds":"New Mexico St Aggies","espn":""},
{"canonical":"North Dakota St.","bart":"North Dakota St.","odds":"North Dakota St Bison","espn":""},
{"canonical":"Northern Arizona","bart":"Northern Arizona","odds":"Northern Arizona Lumberjacks","espn":""},
{"canonical":"Northwestern","bart":"Northwestern","odds":"Northwestern Wildcats","espn":""},
{"canonical":"Notre Dame","bart":"Notre Dame","odds":"Notre Dame Fighting Irish","espn":""},
{"canonical":"Ohio St.","bart":"Ohio St.","odds":"Ohio State Buckeyes","espn":""},
{"canonical":"Oklahoma","bart":"Oklahoma","odds":"Oklahoma Sooners","espn":""},
{"canonical":"Mississippi","bart":"Mississippi","odds":"Ole Miss Rebels","espn":""},
{"canonical":"Oregon","bart":"Oregon","odds":"Oregon Ducks","espn":""},
{"canonical":"Pacific","bart":"Pacific","odds":"Pacific Tigers","espn":""},
{"canonical":"Pittsburgh","bart":"Pittsburgh","odds":"Pittsburgh Panthers","espn":""},
{"canonical":"Princeton","bart":"Princeton","odds":"Princeton Tigers","espn":""},
{"canonical":"Providence","bart":"Providence","odds":"Providence Friars","espn":""},
{"canonical":"Quinnipiac","bart":"Quinnipiac","odds":"Quinnipiac Bobcats","espn":""},
{"canonical":"Rhode Island","bart":"Rhode Island","odds":"Rhode Island Rams","espn":""},
{"canonical":"Richmond","bart":"Richmond","odds":"Richmond Spiders","espn":""},
{"canonical":"SMU","bart":"SMU","odds":"SMU Mustangs","espn":""},
{"canonical":"Sacramento St.","bart":"Sacramento St.","odds":"Sacramento St Hornets","espn":""},
{"canonical":"Saint Joseph's","bart":"Saint Joseph's","odds":"Saint Joseph's Hawks","espn":""},
{"canonical":"Sam Houston St.","bart":"Sam Houston St.","odds":"Sam Houston St Bearkats","espn":""},
{"canonical":"Samford","bart":"Samford","odds":"Samford Bulldogs","espn":""},
{"canonical":"San Francisco","bart":"San Francisco","odds":"San Francisco Dons","espn":""},
{"canonical":"San Jose St.","bart":"San Jose St.","odds":"San José St Spartans","espn":""},
{"canonical":"Siena","bart":"Siena","odds":"Siena Saints","espn":""},
{"canonical":"South Carolina","bart":"South Carolina","odds":"South Carolina Gamecocks","espn":""},
{"canonical":"South Carolina St.","bart":"South Carolina St.","odds":"South Carolina State Bulldogs","espn":""},
{"canonical":"South Carolina St.","bart":"","odds":"","espn":""},
{"canonical":"Southern Utah","bart":"Southern Utah","odds":"Southern Utah Thunderbirds","espn":""},
{"canonical":"St. Thomas","bart":"St. Thomas","odds":"St. Thomas (MN) Tommies","espn":""},
{"canonical":"Stanford","bart":"Stanford","odds":"Stanford Cardinal","espn":""},
{"canonical":"Syracuse","bart":"Syracuse","odds":"Syracuse Orange","espn":""},
{"canonical":"TCU","bart":"TCU","odds":"TCU Horned Frogs","espn":""},
{"canonical":"Texas A&M","bart":"Texas A&M","odds":"Texas A&M Aggies","espn":""},
{"canonical":"Texas","bart":"Texas","odds":"Texas Longhorns","espn":""},
{"canonical":"Texas Tech","bart":"Texas Tech","odds":"Texas Tech Red Raiders","espn":""},
{"canonical":"Towson","bart":"Towson","odds":"Towson Tigers","espn":""},
{"canonical":"UC Davis","bart":"UC Davis","odds":"UC Davis Aggies","espn":""},
{"canonical":"UC Irvine","bart":"UC Irvine","odds":"UC Irvine Anteaters","espn":""},
{"canonical":"UC San Diego","bart":"UC San Diego","odds":"UC San Diego Tritons","espn":""},
{"canonical":"UC Santa Barbara","bart":"UC Santa Barbara","odds":"UC Santa Barbara Gauchos","espn":""},
{"canonical":"UCLA","bart":"UCLA","odds":"UCLA Bruins","espn":""},
{"canonical":"UMBC","bart":"UMBC","odds":"UMBC Retrievers","espn":""},
{"canonical":"UMass Lowell","bart":"UMass Lowell","odds":"UMass Lowell River Hawks","espn":""},
{"canonical":"USC","bart":"USC","odds":"USC Trojans","espn":""},
{"canonical":"UT Arlington","bart":"UT Arlington","odds":"UT-Arlington Mavericks","espn":""},
{"canonical":"UTEP","bart":"UTEP","odds":"UTEP Miners","espn":""},
{"canonical":"Utah St.","bart":"Utah St.","odds":"Utah State Aggies","espn":""},
{"canonical":"Utah Tech","bart":"Utah Tech","odds":"Utah Tech Trailblazers","espn":""},
{"canonical":"Utah","bart":"Utah","odds":"Utah Utes","espn":""},
{"canonical":"Utah Valley","bart":"Utah Valley","odds":"Utah Valley Wolverines","espn":""},
{"canonical":"Vermont","bart":"Vermont","odds":"Vermont Catamounts","espn":""},
{"canonical":"Villanova","bart":"Villanova","odds":"Villanova Wildcats","espn":""},
{"canonical":"Wagner","bart":"Wagner","odds":"Wagner Seahawks","espn":""},
{"canonical":"Wake Forest","bart":"Wake Forest","odds":"Wake Forest Demon Deacons","espn":""},
{"canonical":"Washington","bart":"Washington","odds":"Washington Huskies","espn":""},
{"canonical":"Western Carolina","bart":"Western Carolina","odds":"Western Carolina Catamounts","espn":""},
{"canonical":"Western Kentucky","bart":"Western Kentucky","odds":"Western Kentucky Hilltoppers","espn":""},
{"canonical":"Wichita St.","bart":"Wichita St.","odds":"Wichita St Shockers","espn":""},
{"canonical":"William & Mary","bart":"William & Mary","odds":"William & Mary Tribe","espn":""},
{"canonical":"Wofford","bart":"Wofford","odds":"Wofford Terriers","espn":""},
{"canonical":"Wyoming","bart":"Wyoming","odds":"Wyoming Cowboys","espn":""},
{"canonical":"Xavier","bart":"Xavier","odds":"Xavier Musketeers","espn":""},
{"canonical":"Yale","bart":"Yale","odds":"Yale Bulldogs","espn":""},
{"canonical":"Drake","bart":"Drake","odds":"Drake Bulldogs","espn":""},
{"canonical":"Northern Iowa","bart":"Northern Iowa","odds":"Northern Iowa Panthers","espn":""},
{"canonical":"Southern Miss","bart":"Southern Miss","odds":"Southern Miss Golden Eagles","espn":""},
{"canonical":"Portland","bart":"Portland","odds":"Portland Pilots","espn":""},
{"canonical":"Georgia Southern","bart":"Georgia Southern","odds":"Georgia Southern Eagles","espn":""},
{"canonical":"Boston University","bart":"Boston University","odds":"Boston Univ. Terriers","espn":""},
{"canonical":"Charleston","bart":"Charleston","odds":"Charleston Cougars","espn":""},
{"canonical":"Charlotte","bart":"Charlotte","odds":"Charlotte 49ers","espn":""},
{"canonical":"Colgate","bart":"Colgate","odds":"Colgate Raiders","espn":""},
{"canonical":"East Carolina","bart":"East Carolina","odds":"East Carolina Pirates","espn":""},
{"canonical":"Green Bay","bart":"Green Bay","odds":"Green Bay Phoenix","espn":""},
{"canonical":"Hofstra","bart":"Hofstra","odds":"Hofstra Pride","espn":""},
{"canonical":"Houston Christian","bart":"Houston Christian","odds":"Houston Christian Huskies","espn":""},
{"canonical":"Illinois","bart":"Illinois","odds":"Illinois Fighting Illini","espn":""},
{"canonical":"Iowa","bart":"Iowa","odds":"Iowa Hawkeyes","espn":""},
{"canonical":"Marshall","bart":"Marshall","odds":"Marshall Thundering Herd","espn":""},
{"canonical":"Maryland","bart":"Maryland","odds":"Maryland Terrapins","espn":""},
{"canonical":"Memphis","bart":"Memphis","odds":"Memphis Tigers","espn":""},
{"canonical":"Michigan","bart":"Michigan","odds":"Michigan Wolverines","espn":""},
{"canonical":"Michigan St.","bart":"Michigan St.","odds":"Michigan St Spartans","espn":""},
{"canonical":"Monmouth","bart":"Monmouth","odds":"Monmouth Hawks","espn":""},
{"canonical":"Montana St.","bart":"Montana St.","odds":"Montana St Bobcats","espn":""},
{"canonical":"Nebraska","bart":"Nebraska","odds":"Nebraska Cornhuskers","espn":""},
{"canonical":"New Orleans","bart":"New Orleans","odds":"New Orleans Privateers","espn":""},
{"canonical":"Nicholls St.","bart":"Nicholls St.","odds":"Nicholls St Colonels","espn":""},
{"canonical":"Oregon St.","bart":"Oregon St.","odds":"Oregon St Beavers","espn":""},
{"canonical":"Penn St.","bart":"Penn St.","odds":"Penn State Nittany Lions","espn":""},
{"canonical":"Portland St.","bart":"Portland St.","odds":"Portland St Vikings","espn":""},
{"canonical":"Rice","bart":"Rice","odds":"Rice Owls","espn":""},
{"canonical":"Rutgers","bart":"Rutgers","odds":"Rutgers Scarlet Knights","espn":""},
{"canonical":"Santa Clara","bart":"Santa Clara","odds":"Santa Clara Broncos","espn":""},
{"canonical":"South Florida","bart":"South Florida","odds":"South Florida Bulls","espn":""},
{"canonical":"Temple","bart":"Temple","odds":"Temple Owls","espn":""},
{"canonical":"Troy","bart":"Troy","odds":"Troy Trojans","espn":""},
{"canonical":"Tulane","bart":"Tulane","odds":"Tulane Green Wave","espn":""},
{"canonical":"Tulsa","bart":"Tulsa","odds":"Tulsa Golden Hurricane","espn":""},
{"canonical":"UAB","bart":"UAB","odds":"UAB Blazers","espn":""},
{"canonical":"UNC Wilmington","bart":"UNC Wilmington","odds":"UNC Wilmington Seahawks","espn":""},
{"canonical":"UTSA","bart":"UTSA","odds":"UTSA Roadrunners","espn":""},
{"canonical":"Fairfield","bart":"Fairfield","odds":"Fairfield Stags","espn":""},
{"canonical":"Lehigh","bart":"Lehigh","odds":"Lehigh Mountain Hawks","espn":""},
{"canonical":"Lehigh","bart":"Lehigh","odds":"Lehigh Pat-T","espn":""},
{"canonical":"Navy","bart":"Navy","odds":"Navy Midshipmen","espn":""},
{"canonical":"Navy","bart":"Navy","odds":"Navy Pat-T","espn":""},
{"canonical":"New Orleans","bart":"New Orleans","odds":"New Orleans Slnd-T","espn":""},
{"canonical":"Northern Kentucky","bart":"Northern Kentucky","odds":"Northern Kentucky Norse","espn":""},
{"canonical":"Northern Kentucky","bart":"Northern Kentucky","odds":"Northern Kentucky Horz-T","espn":""},
{"canonical":"Northwestern St.","bart":"Northwestern St.","odds":"Northwestern St Demons","espn":""},
{"canonical":"Northwestern St.","bart":"Northwestern St.","odds":"Northwestern St. Slnd-T","espn":""},
{"canonical":"Alabama St.","bart":"Alabama St.","odds":"Alabama St Hornets","espn":""},
{"canonical":"Alcorn St.","bart":"Alcorn St.","odds":"Alcorn St Braves","espn":""},
{"canonical":"Detroit Mercy","bart":"Detroit Mercy","odds":"Detroit Mercy Titans","espn":""},
{"canonical":"Eastern Washington","bart":"Eastern Washington","odds":"Eastern Washington Eagles","espn":""},
{"canonical":"Grambling St.","bart":"Grambling St.","odds":"Grambling St Tigers","espn":""},
{"canonical":"Mississippi Valley St.","bart":"Mississippi Valley St.","odds":"Miss Valley St Delta Devils","espn":""},
{"canonical":"Montana","bart":"Montana","odds":"Montana Grizzlies","espn":""},
{"canonical":"Northern Colorado","bart":"Northern Colorado","odds":"N Colorado Bears","espn":""},
{"canonical":"Saint Mary's","bart":"Saint Mary's","odds":"Saint Mary's Gaels","espn":""},
{"canonical":"UT Rio Grande Valley","bart":"UT Rio Grande Valley","odds":"UT Rio Grande Valley Vaqueros","espn":""},
{"canonical":"Weber St.","bart":"Weber St.","odds":"Weber State Wildcats","espn":""},
{"canonical":"Wright St.","bart":"Wright St.","odds":"Wright St Raiders","espn":""},
{"canonical":"Robert Morris","bart":"Robert Morris","odds":"Robert Morris Colonials","espn":""},
{"canonical":"Robert Morris","bart":"Robert Morris","odds":"Robert Morris Colonials","espn":""},
{"canonical":"Alabama A&M","bart":"Alabama A&M","odds":"","espn":""},
{"canonical":"American","bart":"American","odds":"","espn":""},
{"canonical":"Arkansas Pine Bluff","bart":"Arkansas Pine Bluff","odds":"","espn":""},
{"canonical":"Arkansas St.","bart":"Arkansas St.","odds":"","espn":""},
{"canonical":"Army","bart":"Army","odds":"","espn":""},
{"canonical":"Bethune Cookman","bart":"Bethune Cookman","odds":"","espn":""},
{"canonical":"Binghamton","bart":"Binghamton","odds":"","espn":""},
{"canonical":"Bucknell","bart":"Bucknell","odds":"","espn":""},
{"canonical":"Canisius","bart":"Canisius","odds":"","espn":""},
{"canonical":"Central Connecticut","bart":"Central Connecticut","odds":"","espn":""},
{"canonical":"Chicago St.","bart":"Chicago St.","odds":"","espn":""},
{"canonical":"Cleveland St.","bart":"Cleveland St.","odds":"","espn":""},
{"canonical":"Coppin St.","bart":"Coppin St.","odds":"","espn":""},
{"canonical":"Creighton","bart":"Creighton","odds":"Creighton Bluejays","espn":""},
{"canonical":"Delaware St.","bart":"Delaware St.","odds":"","espn":""},
{"canonical":"East Texas A&M","bart":"East Texas A&M","odds":"","espn":""},
{"canonical":"Eastern Illinois","bart":"Eastern Illinois","odds":"","espn":""},
{"canonical":"Eastern Kentucky","bart":"Eastern Kentucky","odds":"","espn":""},
{"canonical":"Evansville","bart":"Evansville","odds":"","espn":""},
{"canonical":"Fairleigh Dickinson","bart":"Fairleigh Dickinson","odds":"","espn":""},
{"canonical":"Florida A&M","bart":"Florida A&M","odds":"","espn":""},
{"canonical":"Georgia St.","bart":"Georgia St.","odds":"","espn":""},
{"canonical":"Holy Cross","bart":"Holy Cross","odds":"","espn":""},
{"canonical":"Howard","bart":"Howard","odds":"Howard Bison","espn":""},
{"canonical":"IU Indy","bart":"IU Indy","odds":"","espn":""},
{"canonical":"Incarnate Word","bart":"Incarnate Word","odds":"","espn":""},
{"canonical":"Indiana St.","bart":"Indiana St.","odds":"","espn":""},
{"canonical":"Iona","bart":"Iona","odds":"","espn":""},
{"canonical":"Jackson St.","bart":"Jackson St.","odds":"","espn":""},
{"canonical":"Jacksonville","bart":"Jacksonville","odds":"","espn":""},
{"canonical":"James Madison","bart":"James Madison","odds":"","espn":""},
{"canonical":"Lafayette","bart":"Lafayette","odds":"","espn":""},
{"canonical":"Lamar","bart":"Lamar","odds":"","espn":""},
{"canonical":"Le Moyne","bart":"Le Moyne","odds":"","espn":""},
{"canonical":"Lindenwood","bart":"Lindenwood","odds":"","espn":""},
{"canonical":"Little Rock","bart":"Little Rock","odds":"","espn":""},
{"canonical":"Louisiana","bart":"Louisiana","odds":"","espn":""},
{"canonical":"Louisiana Monroe","bart":"Louisiana Monroe","odds":"","espn":""},
{"canonical":"Loyola MD","bart":"Loyola MD","odds":"","espn":""},
{"canonical":"Loyola Marymount","bart":"Loyola Marymount","odds":"","espn":""},
{"canonical":"Manhattan","bart":"Manhattan","odds":"","espn":""},
{"canonical":"Maryland Eastern Shore","bart":"Maryland Eastern Shore","odds":"","espn":""},
{"canonical":"Massachusetts","bart":"Massachusetts","odds":"","espn":""},
{"canonical":"McNeese St.","bart":"McNeese St.","odds":"","espn":""},
{"canonical":"Milwaukee","bart":"Milwaukee","odds":"","espn":""},
{"canonical":"Morgan St.","bart":"Morgan St.","odds":"","espn":""},
{"canonical":"New Haven","bart":"New Haven","odds":"","espn":""},
{"canonical":"Niagara","bart":"Niagara","odds":"","espn":""},
{"canonical":"Norfolk St.","bart":"Norfolk St.","odds":"","espn":""},
{"canonical":"North Alabama","bart":"North Alabama","odds":"","espn":""},
{"canonical":"North Carolina Central","bart":"North Carolina Central","odds":"","espn":""},
{"canonical":"North Florida","bart":"North Florida","odds":"","espn":""},
{"canonical":"North Texas","bart":"North Texas","odds":"","espn":""},
{"canonical":"Oakland","bart":"Oakland","odds":"","espn":""},
{"canonical":"Old Dominion","bart":"Old Dominion","odds":"","espn":""},
{"canonical":"Oral Roberts","bart":"Oral Roberts","odds":"","espn":""},
{"canonical":"Pepperdine","bart":"Pepperdine","odds":"","espn":""},
{"canonical":"Prairie View A&M","bart":"Prairie View A&M","odds":"","espn":""},
{"canonical":"Purdue Fort Wayne","bart":"Purdue Fort Wayne","odds":"","espn":""},
{"canonical":"Rider","bart":"Rider","odds":"","espn":""},
{"canonical":"SIU Edwardsville","bart":"SIU Edwardsville","odds":"","espn":""},
{"canonical":"Saint Francis","bart":"Saint Francis","odds":"","espn":""},
{"canonical":"South Carolina St.","bart":"South Carolina St.","odds":"","espn":""},
{"canonical":"South Dakota St.","bart":"South Dakota St.","odds":"","espn":""},
{"canonical":"Southeastern Louisiana","bart":"Southeastern Louisiana","odds":"","espn":""},
{"canonical":"Southern","bart":"Southern","odds":"","espn":""},
{"canonical":"Southern Illinois","bart":"Southern Illinois","odds":"","espn":""},
{"canonical":"Southern Indiana","bart":"Southern Indiana","odds":"","espn":""},
{"canonical":"Stephen F. Austin","bart":"Stephen F. Austin","odds":"","espn":""},
{"canonical":"Tarleton St.","bart":"Tarleton St.","odds":"","espn":""},
{"canonical":"Tennessee Tech","bart":"Tennessee Tech","odds":"","espn":""},
{"canonical":"Texas Southern","bart":"Texas Southern","odds":"","espn":""},
{"canonical":"UC Riverside","bart":"UC Riverside","odds":"","espn":""},
{"canonical":"UMKC","bart":"UMKC","odds":"","espn":""},
{"canonical":"USC Upstate","bart":"USC Upstate","odds":"","espn":""},
{"canonical":"UT Rio Grande Valley","bart":"UT Rio Grande Valley","odds":"","espn":""},
{"canonical":"Western Illinois","bart":"Western Illinois","odds":"","espn":""},
{"canonical":"Youngstown St.","bart":"Youngstown St.","odds":"","espn":""},
{"canonical":"Cincinnati","bart":"Cincinn","odds":"","espn":""},
{"canonical":"Colgate","bart":"Colg","odds":"","espn":""},
{"canonical":"Incarnate Word","bart":"Incarn","odds":"","espn":""},
{"canonical":"Manhattan","bart":"Manh","odds":"","espn":""},
{"canonical":"N.C. State","bart":"N.C. St","odds":"","espn":""},
{"canonical":"Seattle","bart":"Se","odds":"","espn":""},
{"canonical":"USC Upstate","bart":"USC Upst","odds":"","espn":""},
{"canonical":"Gonzaga","bart":"Gonzaga","odds":"Gonzaga Bulldogs","espn":""},
{"canonical":"Arizona St.","bart":"Arizona St.","odds":"Arizona St Sun Devils","espn":""},
{"canonical":"Baylor","bart":"Baylor","odds":"Baylor Bears","espn":""},
{"canonical":"Prairie View A&M","bart":"Prairie View A&M","odds":"Prairie View Panthers","espn":""},
{"canonical":"Alcorn St.","bart":"Alcorn St.","odds":"Alcorn St Braves","espn":""},
{"canonical":"Stanford","bart":"Stanford","odds":"Stanford Cardinal","espn":""},
{"canonical":"Pittsburgh","bart":"Pittsburgh","odds":"Pittsburgh Panthers","espn":""},
{"canonical":"Cincinnati","bart":"Cincinnati","odds":"Cincinnati Bearcats","espn":""},
{"canonical":"Utah","bart":"Utah","odds":"Utah Utes","espn":""},
{"canonical":"SMU","bart":"SMU","odds":"SMU Mustangs","espn":""},
{"canonical":"Syracuse","bart":"Syracuse","odds":"Syracuse Orange","espn":""},
{"canonical":"Oregon","bart":"Oregon","odds":"Oregon Ducks","espn":""},
{"canonical":"Maryland","bart":"Maryland","odds":"Maryland Terrapins","espn":""},
{"canonical":"UMBC","bart":"UMBC","odds":"UMBC Retrievers","espn":""},
{"canonical":"UMass Lowell","bart":"UMass Lowell","odds":"UMass Lowell River Hawks","espn":""},
{"canonical":"FIU","bart":"FIU","odds":"Florida Int'l Golden Panthers","espn":""},
{"canonical":"Missouri St.","bart":"Missouri St.","odds":"Missouri St Bears","espn":""},
{"canonical":"BYU","bart":"BYU","odds":"BYU Cougars","espn":""},
{"canonical":"Kansas St.","bart":"Kansas St.","odds":"Kansas St Wildcats","espn":""},
{"canonical":"Wright St.","bart":"Wright St.","odds":"Wright St Raiders","espn":""},
{"canonical":"Detroit Mercy","bart":"Detroit Mercy","odds":"Detroit Mercy Titans","espn":""},
{"canonical":"Hofstra","bart":"Hofstra","odds":"Hofstra Pride","espn":""},
{"canonical":"Monmouth","bart":"Monmouth","odds":"Monmouth Hawks","espn":""},
{"canonical":"LIU","bart":"LIU","odds":"LIU Sharks","espn":""},
{"canonical":"Mercyhurst","bart":"Mercyhurst","odds":"Mercyhurst Lakers","espn":""},
{"canonical":"Vermont","bart":"Vermont","odds":"Vermont Catamounts","espn":""},
{"canonical":"NJIT","bart":"NJIT","odds":"NJIT Highlanders","espn":""},
{"canonical":"Virginia Tech","bart":"Virginia Tech","odds":"Virginia Tech Hokies","espn":""},
{"canonical":"Wake Forest","bart":"Wake Forest","odds":"Wake Forest Demon Deacons","espn":""},
{"canonical":"Stephen F. Austin","bart":"Stephen F. Austin","odds":"Stephen F. Austin Lumberjacks","espn":""},
{"canonical":"Texas A&M Corpus Chris","bart":"Texas A&M Corpus Chris","odds":"Texas A&M-CC Islanders","espn":""},
{"canonical":"Northwestern","bart":"Northwestern","odds":"Northwestern Wildcats","espn":""},
{"canonical":"Penn St.","bart":"Penn St.","odds":"Penn State Nittany Lions","espn":""},
{"canonical":"Jackson St.","bart":"Jackson St.","odds":"Jackson St Tigers","espn":""},
{"canonical":"Grambling St.","bart":"Grambling St.","odds":"Grambling St Tigers","espn":""},
{"canonical":"Gonzaga","bart":"Gonzaga","odds":"Gonzaga Bulldogs","espn":""},
{"canonical":"Santa Clara","bart":"Santa Clara","odds":"Santa Clara Broncos","espn":""},
{"canonical":"Jacksonville St.","bart":"Jacksonville St.","odds":"Jacksonville St Gamecocks","espn":""},
{"canonical":"New Mexico St.","bart":"New Mexico St.","odds":"New Mexico St Aggies","espn":""},
{"canonical":"Merrimack","bart":"Merrimack","odds":"Merrimack Warriors","espn":""},
{"canonical":"Siena","bart":"Siena","odds":"Siena Saints","espn":""},
{"canonical":"Portland St.","bart":"Portland St.","odds":"Portland St Vikings","espn":""},
{"canonical":"Montana","bart":"Montana","odds":"Montana Grizzlies","espn":""},
{"canonical":"Colorado","bart":"Colorado","odds":"Colorado Buffaloes","espn":""},
{"canonical":"Oklahoma St.","bart":"Oklahoma St.","odds":"Oklahoma St Cowboys","espn":""},
{"canonical":"McNeese St.","bart":"McNeese St.","odds":"McNeese Cowboys","espn":""},
{"canonical":"UT Rio Grande Valley","bart":"UT Rio Grande Valley","odds":"UT Rio Grande Valley Vaqueros","espn":""},
{"canonical":"Eastern Washington","bart":"Eastern Washington","odds":"Eastern Washington Eagles","espn":""},
{"canonical":"Idaho","bart":"Idaho","odds":"Idaho Vandals","espn":""},
{"canonical":"Arkansas Pine Bluff","bart":"Arkansas Pine Bluff","odds":"Arkansas-Pine Bluff Golden Lions","espn":""},
{"canonical":"Maryland Eastern Shore","bart":"Maryland Eastern Shore","odds":"Maryland-Eastern Shore Hawks","espn":""},
{"canonical":"Norfolk St.","bart":"Norfolk St.","odds":"Norfolk St Spartans","espn":""},
{"canonical":"Delaware St.","bart":"Delaware St.","odds":"Delaware State Hornets","espn":""},
]
