TOURNAMENT_MODE = True

# Spread/totals bet filters
REGULAR_SPREAD_EDGE_MIN = 6.0
REGULAR_SPREAD_EDGE_MAX = 12.0
TOURNAMENT_SPREAD_EDGE_MIN = 6.0
TOURNAMENT_SPREAD_EDGE_MAX = 10.0

TOTAL_EDGE_MIN = 6.0
TOTAL_EDGE_MAX = 12.0

# Projection tuning
REGULAR_HOME_COURT = 3.0
TOURNAMENT_HOME_COURT = 0.0

REGULAR_RECENCY_MULTIPLIER = 1.0
TOURNAMENT_RECENCY_MULTIPLIER = 0.5


def spread_edge_band():
    if TOURNAMENT_MODE:
        return TOURNAMENT_SPREAD_EDGE_MIN, TOURNAMENT_SPREAD_EDGE_MAX
    return REGULAR_SPREAD_EDGE_MIN, REGULAR_SPREAD_EDGE_MAX


def active_home_court():
    if TOURNAMENT_MODE:
        return TOURNAMENT_HOME_COURT
    return REGULAR_HOME_COURT


def active_recency_multiplier():
    if TOURNAMENT_MODE:
        return TOURNAMENT_RECENCY_MULTIPLIER
    return REGULAR_RECENCY_MULTIPLIER


def active_mode_label():
    return "TOURNAMENT" if TOURNAMENT_MODE else "REGULAR"
